name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: wget https://ci.tivy.ca/view/Purpur/job/Airplane-Purpur-1.17/lastSuccessfulBuild/artifact/launcher-airplanepurpur.jar
      - name: upload file
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./
