name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Download file
        run: wget https://ci.tivy.ca/view/Purpur/job/Airplane-Purpur-1.17/lastSuccessfulBuild/artifact/launcher-airplanepurpur.jar
      - name: upload file
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./
